package io.sengage.webservice.model;

import io.sengage.webservice.persistence.converters.InstantConverter;

import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEnum;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedJson;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBVersionAttribute;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Builder(toBuilder = true)
@AllArgsConstructor
@NoArgsConstructor
@Data
@DynamoDBTable(tableName = GameItem.TABLE_NAME)
public class GameItem {
	public static final String TABLE_NAME = "Game";
	public static final String GAME_ID_ATTR = "GameId";
	public static final String CHANNEL_ID_ATTR = "channelId";
	public static final String GAME_STATUS_ATTR = "gameStatus";
	public static final String CREATED_AT_ATTR = "createdAt";
	public static final String CHANNEL_ID_GAME_STATUS_INDEX = CHANNEL_ID_ATTR + "-" + GAME_STATUS_ATTR + "-Index";
	
	@DynamoDBHashKey(attributeName = GAME_ID_ATTR)
	@DynamoDBAutoGeneratedKey
	private String gameId;
	@DynamoDBIndexHashKey(attributeName = CHANNEL_ID_ATTR, globalSecondaryIndexName = CHANNEL_ID_GAME_STATUS_INDEX)
	private String channelId;
	private String userId;
	private String userName;
	private String opaqueId;
	@DynamoDBTypeConvertedEnum
	private Game game;
	@DynamoDBIndexRangeKey(attributeName = GAME_STATUS_ATTR, globalSecondaryIndexName = CHANNEL_ID_GAME_STATUS_INDEX)
	@DynamoDBTypeConvertedEnum
	private GameStatus gameStatus;
	private String statusReason;
	@DynamoDBTypeConverted(converter = InstantConverter.class)
	@DynamoDBAttribute(attributeName = CREATED_AT_ATTR)
	private Instant createdAt;
	@DynamoDBTypeConverted(converter = InstantConverter.class)
	private Instant modifiedAt;
	@DynamoDBTypeConvertedJson
	private GameSpecificParameters gameSpecificParameters;
	private int duration;
	private String startGameStateMachineExecutionArn;
	private String gameTimeUpStateMachineExecutionArn;
	private Long version;
	
	public void setVersion(Long version) {
		this.version = version;
	}
	
	@DynamoDBVersionAttribute
	public Long getVersion() {
		return version;
	}
	
	public static GameItem from(Game game, GameSpecificParameters parameters, 
			int duration, StreamContext streamContext) {
		Instant now = Instant.now();
		
		return GameItem.builder()
		.game(game)
		.gameSpecificParameters(parameters)
		.duration(duration)
		.gameStatus(GameStatus.INIT)
		.opaqueId(streamContext.getOpaqueId())
		.channelId(streamContext.getChannelId())
		.userId(streamContext.getUserId()) // todo add username
		.createdAt(now)
		.modifiedAt(now)
		.build();
	}
	
	public GameItemDigest toDigest() {
		return new GameItemDigest(gameId, game);
	}
	
	@DynamoDBIgnore
	public List<String> getStateMachineArns() {
		List<String> arns = new ArrayList<>(2);
		if (startGameStateMachineExecutionArn != null) {
			arns.add(startGameStateMachineExecutionArn);
		}
		if (gameTimeUpStateMachineExecutionArn != null) {
			arns.add(gameTimeUpStateMachineExecutionArn);
		}
		
		return arns;
	}
	
	@DynamoDBIgnore
	public Instant getCompletesAt() {
		return getCreatedAt().plus(getDuration(), ChronoUnit.SECONDS);
	}
	
	@Data
	@AllArgsConstructor
	@NoArgsConstructor
	public static class GameItemDigest {
		public static final String GAME_ID_ATTR_KEY = "gameId";
		public static final String GAME_ATTR_KEY = "game";
		private String gameId;
		private Game game;
	}
}
